### ISSUE TITLE
Possibilité de se tuer avec ses propres projectiles

### ISSUE THREAD

**Issue by serBM** [KmxCronos/PLA-Groupe2#2]
Lorsque le joueur se déplace et lance des projectiles en même temps, il se touche régulièrement avec ses propres projectiles

**Comment by KmxCronos** [comment]
Bonjour Maxence, tout d'abord merci pour l'intérêt que vous portez à notre projet, le bug que vous venez de signaler a été transmis à notre équipe technique.
Un correctif sera proposé ASAP.

Cordialement,
Le J
